# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3a9019e9cea55ea99f3c291d6a9e2353e18aaf2119a86beb3ab181f1f18c19105b66a94d44a2011331d8b8e9b25d4dc5e749b9e013c270d1e717b9611b469a

test:
  secret_key_base: 812c54814bb3e8f250d93a418ba384d03efbda7f93448caca01e7821eda9620dc9832caf812f425692fe74af2c58a7dac3daf71d7391aec6c16a1affb6bcfdc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
